type = "Item"
itemType = "Weapon"

[[messages]]
text = "There's a sword shop in Varrock."

[[messages]]
text = "I would recommend a shortsword. They attack quickly and deal moderate damage."

[[requirements]]
type = "Skill"
name = "Attack"
level = 1
levelMax = 39
